sudo: required
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
env:
  - CMAKEFLAGS=-DBUILD_SDL2=ON
  - CMAKEFLAGS=-DBUILD_SDL2=OFF
before_install:
  - sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug CMAKEFLAGS
script:
  - make
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
  packages:
    - gcc-4.8
    - g++-4.8
    - clang
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7bd6ea617ffcfb529f4f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: alway
